- name: GP Security Scan
  # You may pin to the exact commit or the version.
  # uses: whitesource/GitHubPackagesSecurityAction@b5f36d0e95550dd5699e967862e882fcee19fa2c
  uses: whitesource/GitHubPackagesSecurityAction@19.10.2
  with:
    # GitHub access token with read/write privileges to GitHub Packages
    gp-token: 
    # WS environment destination url
    ws-destination-url: 
    # WS organization api key
    ws-api-key: 
    # WS user key
    ws-user-key: 
    # WS product key to publish results to
    ws-product-key: # optional
    # Whether to print the results report
    print-scan-report: # optional
    # Whether to print debug logs
    actions_step_debug: # optional
