name: Deploy Java app to Azure Web App

on:
  [push]

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_WEBAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_WEBAPP_NAME: 'demoJavaSpringPetclinic'  # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }} # set this to the path to your web app project
  JAVA_VERSION: '1.8'                # set this to the node version to use
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}     # set GH repo secret with the publish profile of the web app

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: 'Deploy to Azure WebApp'
    - name: Azure Login
        uses: Azure/login@v1
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
           creds: '${{ secrets.AZURE_CREDENTIALS }}'
          # ClientId of the Azure Service principal created.
           #client-id: # optional
            # TenantId of the Azure Service principal created.
           #tenant-id: # optional
          # Azure subscriptionId
           #subscription-id: # optional
          # Set this value to true to enable Azure PowerShell Login in addition to Az CLI login
           enable-AzPSSession: 'true'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: 'demojavaspringpetclinic'
        publish-profile: '${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}'
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/target/*.jar'
        
  # For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
  # For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
